Tweaks to publish

diff --git a/bin/publish b/bin/publish
--- a/bin/publish
+++ b/bin/publish
@@ -18,21 +18,24 @@ function run_ig_publisher {
   fi
 
   if [ $? -ne 0 ] ; then
-    echo "Error updating publisher"
+    echo "!!! Error updating publisher"
+    exit 1
   fi
 
   echo "* Running IG Publisher"
   ( cd $FSHTANK && chmod 0755 *.sh && JAVA_OPTS=$JAVA_OPTS ./_genonce.sh )
 
   if [ $? -ne 0 ] ; then
-    echo "Error running publisher"
+    echo "!!! Error running publisher"
+    exit 1
   fi
 
   echo "* Make a copy of /docs for GH pages"
   ( cd $FSHTANK && cp -ap ./output ./docs/ )
 
   if [ $? -ne 0 ] ; then
-    echo "Error copying"
+    echo "!!! Error copying"
+    exit 1
   fi
 }
 
